#:kivy 1.0.9

<Base>:
    canvas:
        Rectangle:
            source: './images/base.gif'
            size: self.size

<Game>:
    canvas:
        Rectangle:
            source: './images/background.png'
            pos: self.pos
            size: self.size

    Label:
        font_size: 30
        center_x: root.width - 140
        top: root.top
        text: "Score: 0"

    Base:
        center: self.parent.center